[workspace]
members = [
    "server",
    "domain",
    "errors",
    "minus1",
    "day1",
    "day4",
    "day5",
    "day6",
    "day7",
    "day8",
    "day11",
    "day12",
    "day13",
]

resolver = "2"
