[package]
name = "errors"
version = "13.1.0"
edition = "2021"

[lib]
name = "errors"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.2"
