[package]
name = "day12"
version = "12.1.0"
edition = "2021"

[lib]
name = "day12_endpoints"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.5"
axum-macros = "0.4.0"
domain = { path = "../domain" }
